### ISSUE TITLE
licensing issues ?

### ISSUE THREAD

**Issue by gedw99** [oltrenuovefrontiere/fluttercouch#1]
Nice stuff..

Do you know if i can use this for projects ? For example do Couchbase allow its use for commercial projects if you dont need support ? No idea..

**Comment by oltrenuovefrontiere** [comment]
The fluttercouch package has no explicit licence yet (but will be
opensource), and this is the licence note present in the couchbase mobile
package:

1. License Grant. Couchbase Inc. hereby grants Licensee, free of
charge, the non-exclusive right to use, copy, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
Licensee including the following copyright notice in all copies or
substantial portions of the Software:

Couchbase ®http://www.couchbase.com
Copyright 2018 Couchbase, Inc.



Il Sab 23 Giu 2018, 12:58 gedw99 <notifications@github.com> ha scritto:

**Comment by gedw99** [comment]
Looks pretty much do what you want with it license :)

Awesome to see this !

If you have a roadmap let me know and I can help
