### ISSUE TITLE
Can Not Run the Example App

### ISSUE THREAD

**Issue by sh0umik** [oltrenuovefrontiere/fluttercouch#2]
Just downloaded and Tried to Run the App, but its not running I am getting this message below 

```
E/DB      ( 9973): Cannot load native library
E/zygote64( 9973): No implementation found for void com.couchbase.litecore.C4Log.setLevel(java.lang.String, int) (tried Java_com_couchbase_litecore_C4Log_setLevel and Java_com_couchbase_litecore_C4Log_setLevel__Ljava_lang_String_2I)
```

Any Clue why ?

**Comment by oltrenuovefrontiere** [comment]
Could you tell me more information about your development environment? (Operating System, Android Studio/Visual Studio/other IDE or no IDE at all, emulator used).

This way I could find the problem easier and faster.

**Comment by zxyang178** [comment]
@oltrenuovefrontiere 
I have the same error:

E/DB: Cannot load native library
 E/art: No implementation found for void com.couchbase.litecore.C4Log.setLevel(java.lang.String, int) (tried Java_com_couchbase_litecore_C4Log_setLevel and Java_com_couchbase_litecore_C4Log_setLevel__Ljava_lang_String_2I)
environment:
Win10 x64,android studio 3.0.1,test real Mobile(it have no error at emulator).
@sh0umik  do you have resolve it?and can you post your method?

**Comment by DhudumVishal** [comment]
@oltrenuovefrontiere 
Please check the [file](https://drive.google.com/file/d/1IqjnwRpLL9Rp2cPU24jEBzxM75qSnBRV/view?usp=sharing), it has the error log for running example app. Following errors were hit
1. unable to start replication
2. MissingPluginException(No implementation found for method execute on channel it.oltrenuovefrontiere.fluttercouchJson)

I am using Windows 10 x64, Visual Studio Code, Emulater and mobile both are giving above mentioned error. Please let me know if I can help in any way.

@zxyang178 @sh0umik 
have you found any way to connect to CouchBase?

**Comment by DhudumVishal** [comment]
@oltrenuovefrontiere 
I am new to flutter. I have downloaded the repository and had run the example app from your repository without making any changes. Do we need to add any thing to run the example app. Could you please add the documentation on how to use the plugin. Also please add the version number for adding it as dependency in other project.

[main.dart](https://github.com/oltrenuovefrontiere/fluttercouch/blob/master/example/lib/main.dart)

**Comment by DhudumVishal** [comment]
I am new to Flutter and Couchbase. The issue is due to wrong setReplicatorEndpoint I have set. I have created a server for Couchbase and using a sample bucket called "travel-sample". Please tell me about the URL which needs to be added in it.
And can you please provide some documentation of the methods inside `initPlatformState()` of you examples main.dart file and how to use the plugin overall.

**Comment by oltrenuovefrontiere** [comment]
As you can see in the Couchbase Documentation, Couchbase Lite (the library underlying FlutterCouch implementation) cannot directly sync with Couchbase Server. A Couchbase Sync Gateway has to be deployed with the next instructions to allow syncing between the server and the mobile databases:
```
            "enable_shared_bucket_access": true,
            "import_docs": "continuous",
```
You can find further documentation about Couchbase Sync Gateway [here](https://docs.couchbase.com/sync-gateway/2.1/getting-started.html).

I'll document the package as soon as possible, so you can use it in your applications.

Thank you for the patience and for the feedbacks.

**Comment by oltrenuovefrontiere** [comment]
As requested, I've added documentation about Fluttercouch currently implementation.
You are welcome to submit any other request or issue at any time, I'll answer ASAP.

**Comment by vishaldhudum** [comment]
Thanks that was helpful. Could you also document how to use Channels in fluttercouch.

**Comment by vishaldhudum** [comment]
I am suppose to start sync with a document which will have data for channel.
From documentation I understood how to save a document and start replication, but how should I start replication with the document which will have credentials and the channel data for replication.

**Comment by vishaldhudum** [comment]
Consider the [code here](https://forums.couchbase.com/t/adding-documents-with-a-channel-and-then-syncing-via-channel-filtering/3757)

What i want to do is send channel data and then replicate using that channel. Similar to this
push.Start();
pull.Start();

But I don't think FlutterCouch supports this. Do we have any alternative.

**Comment by oltrenuovefrontiere** [comment]
At the moment fluttercouch doesn't support specifying a filter for replication, but it is possible to add that functionality. You can open a new issue to request a new feature and I will implement it ASAP.
By the way, at the moment you can create a channel as specified here https://docs.couchbase.com/sync-gateway/2.1/data-routing.html and grant read access to a user only to that channel. Then specify PUSH_AND_PULL as replication type and start the replication. The replicator will replicate (in both dlrections) only channels/docs which user has read access to.
